### ISSUE TITLE
Authorized error

### ISSUE THREAD

**Issue by jrrcdev** [johnknoop/MongoRepository#6] opened 2019-08-11 19:49 UTC
I'm getting "not authorized on [database_name] to execute command: aggregation" on try to use this package.

The MongoClient works ok.

My config code:

```
MongoRepository.Configure()
                    .Database(database, db =>
                        db.Map<User>("Users")
                        .Map<Contact>("Contacts"))
                    .Build();
```

**Comment by johnknoop** [comment] 2019-08-12 15:03
That sounds really weird. No DB commands should be executed by your sample code above. Do you have a full project you can share?

**Comment by jrrcdev** [comment] 2019-08-12 15:07
That code is not where the error happens, the error happens when I try to use some command, like aggregation here:

```
Users = mongoClient.GetRepository<User>();
            Contacts = mongoClient.GetRepository<Contact>();

var query = Contacts
                .Aggregate()
                .Match(c => c.UserId == userId && (withoutUser || !string.IsNullOrEmpty(c.ContactUserId)))
                .Lookup(MongoDatabase.GetCollection<User>("Users"), c => c.ContactUserId, u => u.Id, (Contact c) => c.ContactUsers);
```

**Comment by jrrcdev** [comment] 2019-08-12 15:08
Well, I start the mongo client config like this:

```
var server = configuration.GetValue<string>("MongoDB");
                var port = configuration.GetValue<int>("MongoDBPort");
                var database = configuration.GetValue<string>("MongoDBName");
                var user = configuration.GetValue<string>("MongoDBUser");
                var password = configuration.GetValue<string>("MongoDBPassword");

                IMongoClient client = new MongoClient(new MongoClientSettings()
                {
                    Server = new MongoServerAddress(server, port),
                    Credential = MongoCredential.CreateCredential(database, user, password)
                });

                services.AddSingleton(client);
```

**Comment by johnknoop** [comment] 2019-08-12 15:17
And if you swap the first block of code for:

```csharp
Users = mongoClient.GetCollection<User>("Users");
Contacts = mongoClient.GetCollection<Contact>("Users");
```

and then do the same aggregation, you don't get an error?

**Comment by jrrcdev** [comment] 2019-08-12 17:58
Yes, same

**Comment by jrrcdev** [comment] 2019-08-12 18:37
This works:

```
var models = Contacts // IMongoCollection
                    .Aggregate()
                    .Lookup(
                        foreignCollection: Users,
                        localField: c => c.ContactUserId,
                        foreignField: c => c.Id,
                        (Contact c) => c.ContactUsers
                    );
```

Dont work:

```
var models = ContactsRepo // Your repo object 
                    .Aggregate()
                    .Lookup(
                        foreignCollection: Users,
                        localField: c => c.ContactUserId,
                        foreignField: c => c.Id,
                        (Contact c) => c.ContactUsers
                    );
```

This don't work too:

`ContactsRepo.Find(c => c.Deleted == false);`

**Comment by johnknoop** [comment] 2019-08-13 09:00
@jrrcdev Could you show me what your Contact and User classes look like, and I'll try to reproduce it.

**Comment by jrrcdev** [comment] 2019-08-13 10:45
Added you to a fork of the project

I forgot to mention, it's a net core 3.0 project.

You just need to added the code above and edit the database connection on appsettings.json to a mongo database.

Thanks

**Comment by johnknoop** [comment] 2019-08-16 14:44
@jrrcdev how do I trigger the ContactController.

I'm firing off a request on this url:
![image](https://user-images.githubusercontent.com/3394270/63175838-1d65d480-c045-11e9-9e19-89e0d59fddd3.png)

But it doesn't seem to activate the ContactController.

**Comment by johnknoop** [comment] 2019-08-26 14:38
@jrrcdev are you still having issues? Otherwise I'll close this issue.

**Comment by jrrcdev** [comment] 2019-08-26 14:49
Hi, yes, just give me a moment and I will answer you, last days are too busy. Thanks

**Comment by jrrcdev** [comment] 2019-08-28 10:57
Hello, John.

The url is http://localhost:5000/Contact not Contacts

**Comment by johnknoop** [comment] 2019-08-29 09:33
I need to create a user in order to be able to reproduce it right? How do I do that?

**Comment by jrrcdev** [comment] 2019-08-29 13:21
You can make it anonymous, here a exemple that reproduce the error:

```
[HttpGet]
        [AllowAnonymous]
        [Route("anon")]
        public IActionResult GetAllAnon()
        {
            try
            {

                var models = ContactsRepo
                    .Aggregate()
                    .Lookup(Users,
                        c => c.ContactUserId,
                        u => u.Id,
                        (Contact c) => c.ContactUsers).ToList();


                return Ok(new ResultModel<IEnumerable<ContactViewModel>>()
                {
                    Model = Mapper.Map<IEnumerable<ContactViewModel>>(models)
                });
            }
            catch (Exception e)
            {
                return StatusCode(500, new ResultModel<IEnumerable<ContactViewModel>>()
                {
                    Errors = AddErrors(e)
                });
            }
        }
```

**Comment by jrrcdev** [comment] 2019-08-29 13:22
URL: http://localhost:5000/contact/anon

The error: 

`{"model":null,"errors":{"addErrors":["Command aggregate failed: not authorized on MarketChatdev to execute command { aggregate: \"Contacts\", pipeline: [ { $lookup: { from: \"Users\", localField: \"ContactUserId\", foreignField: \"_id\", as: \"ContactUsers\" } } ], cursor: {}, $db: \"MarketChatdev\", lsid: { id: UUID(\"968793ff-3ca9-4f7a-8760-a31abfe09d5e\") } }."]},"params":null,"isValid":false}`

**Comment by johnknoop** [comment] 2019-08-29 14:19
I get no error from that route:

![image](https://user-images.githubusercontent.com/3394270/63948199-8b17f480-ca78-11e9-9c6e-8fea8170a121.png)

Do I need some Contacts in the database to make it crash?

**Comment by jrrcdev** [comment] 2019-08-29 14:27
Nope, here it crashes always

What are your mongo settings? local? Remote?

**Comment by jrrcdev** [comment] 2019-08-29 14:40
I guess I discovery the problem, my database has a _ in the name, "MarketChat_dev", as you can see in the above comment showing the error, the name is without the _, $db: \"MarketChatdev\". Is your code removing it from the name?

**Comment by jrrcdev** [comment] 2019-08-29 14:43
Using a database without the _ in the name now I'm getting "Unable to authenticate using sasl protocol mechanism SCRAM-SHA-1.","Command saslStart failed: Authentication failed.."

**Comment by johnknoop** [comment] 2019-08-29 15:05
I used a database without any authentication at all turned on.

Could you paste a stack trace of an exception?

**Comment by jrrcdev** [comment] 2019-08-29 15:08
```
   at MongoDB.Driver.Core.Connections.BinaryConnection.OpenHelper(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Connections.BinaryConnection.Open(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.PooledConnection.Open(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquiredConnection.Open(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Servers.Server.GetChannel(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Bindings.ServerChannelSource.GetChannel(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Bindings.ChannelSourceHandle.GetChannel(CancellationToken cancellationToken)
   at MongoDB.Driver.Core.Operations.AggregateOperation`1.Execute(IReadBinding binding, CancellationToken cancellationToken)
   at MongoDB.Driver.OperationExecutor.ExecuteReadOperation[TResult](IReadBinding binding, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, ReadPreference readPreference, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.ExecuteReadOperation[TResult](IClientSessionHandle session, IReadOperation`1 operation, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.Aggregate[TResult](IClientSessionHandle session, PipelineDefinition`2 pipeline, AggregateOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.<>c__DisplayClass19_0`1.<Aggregate>b__0(IClientSessionHandle session)
   at MongoDB.Driver.MongoCollectionImpl`1.UsingImplicitSession[TResult](Func`2 func, CancellationToken cancellationToken)
   at MongoDB.Driver.MongoCollectionImpl`1.Aggregate[TResult](PipelineDefinition`2 pipeline, AggregateOptions options, CancellationToken cancellationToken)
   at MongoDB.Driver.AggregateFluent`2.ToCursor(CancellationToken cancellationToken)
   at MongoDB.Driver.IAsyncCursorSourceExtensions.ToList[TDocument](IAsyncCursorSource`1 source, CancellationToken cancellationToken)
   at MarketChat.Api.Controllers.ContactController.GetAllAnon() in D:\Dev\Repos\MarketChat\MarketChat.Api\MarketChat.Api\Controllers\ContactController.cs:line 132
```

**Comment by johnknoop** [comment] 2019-08-30 10:04
I'm not really sure what to do with this issue. The stacktrace doesn't involve any code from this repository and I can't reproduce the error.

Are you certain that you don't wire up the IMongoCollection<T> differently from the IRepository<T> some how?

We don't really do anything with authorization in this library, since all that is taken care of by the driver.

**Comment by jrrcdev** [comment] 2019-08-30 11:11
I tested with my database server and with mlab server, I got the same error, can you reproduce with mlab server?

**Comment by jrrcdev** [comment] 2019-08-30 11:33
Forget this last error, it was my mistake.

About the other error, database with _ in the name do not work, without _ is working.

Thanks

**Closed as completed** 2020-08-02 15:48 UTC
Labels: cant-reproduce
